### ISSUE TITLE
Failed to obtain package metadata

### ISSUE THREAD

**Issue by igdeman** [blockworks-foundation/ido-pool#3]
Hi there, i have issue running this project. I've been following instruction but unfortunately without any luck. When try to run anchor test i get this error;

Failed to obtain package metadata: Error during execution of `cargo metadata`: error: failed to load manifest for workspace member `/home/.../ido-pool/programs/ido-pool`

Caused by:
  failed to load manifest for dependency `anchor-lang`

Caused by:
  failed to read `/home/.../lang/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

**Comment by microwavedcola1** [comment]
@igdeman fwiw the original author has a newer version here https://github.com/project-serum/anchor/tree/master/tests/ido-pool

**Comment by igdeman** [comment]
> @igdeman fwiw the original author has a newer version here https://github.com/project-serum/anchor/tree/master/tests/ido-pool

Thank you very much, you saved my day!!!
